### ISSUE TITLE
Rebind F keys to do as their icon suggests.

### ISSUE THREAD

**Issue by ColtonDRG** [GalliumOS/galliumos-device-c710#4]
Here is a photograph of the keyboard. The row of keys at the top should be rebound to do as the icon suggests. The keyboard has an "fn" key that should be used as a modifier to access the original "F" key if needed. There should be an option in the settings to modify this behaviour. The WiFi key (F11) should only be activated if some other modifier key is held, or perhaps it can open a WiFi menu instead of toggling the card. Perhaps F12 can be a custom function since it has no icon. I don't know how this layout differs from the rest of Chromebooks, so this functionality may be different depending on the device.
![img_20150907_133544](https://cloud.githubusercontent.com/assets/5587661/9722218/2d1153d0-5566-11e5-9bb1-2dc0481d12d2.jpg)

**Comment by coolstar** [comment]
This is how the keys are laid out on the C720. The labels are the same although it's limited up to F10.
![image](https://cloud.githubusercontent.com/assets/1431548/9722705/fe77f6d6-5566-11e5-983f-efe36ee91dcc.jpg)

**Comment by ColtonDRG** [comment]
Ah, alright. Something will have to be done to accommodate F11 and F12 should they be needed. We will also need to work out an fn key for those newer models as well. It does seem that since they are the same, we should put this in the base, though it should be noted that these should NOT apply to Chromeboxes and Chromebases. Perhaps we need a galliumos-laptop package for differences that are universal for Chromebook models, but don't matter for Chromebox models. Future discussion for this issue should take place in the galliumos-base issue tracker here. https://github.com/GalliumOS/galliumos-base/issues/2

**Comment by hugegreenbug** [comment]
I'm currently using xbindkeys for this. My current config uses the search key + the fn key to perform the action on the label (brightness and volume right now). The others (f1-f5) with the search key, well emulate home, end, page up, page down, and delete. See the config here: https://github.com/GalliumOS/galliumos-haswell/blob/master/etc/skel/.xbindkeysrc . For each galliumos- package, I have an xbindkeysrc file in it. They are currently all the same, but we can change them as needed. We'll have to vote on the final configuration. This is just what I have right now.

For chromebooks that use ACPI for brightness and volume keys, we don't need to touch the brightness keys, but we can add rules for the volume keys in the .xbindkeysrc. The only one I know that needs this is the HP Chromebook 14. We'll need someone to run xbindkeys -k and press the keys.

**Comment by ColtonDRG** [comment]
Alright, that makes sense for most of them, but Chromeboxes, and this model will need separate configurations because this model has the home, insert, end, delete, pageup, and pagedown keys. It should be noted that ChromeOS uses Alt+Backspace for delete, so we may want to consider mimicking that. I still think that we should also have some way to modify this behaviour in the settings as well.

**Comment by hugegreenbug** [comment]
I planned for separate configs. Once the test build is out (hopefully
tonight), we can agree on the key bindings and you can modify the
.xbindkeysrc to match what we agree on and your device. The keyboard
settings program in XFCE does not support these more complex key bindings.
There is a GUI for xbindkeys called xbindkeys-config. We can try to include
that in the settings dialog.

Hugh

**Comment by ColtonDRG** [comment]
Sounds good. Another point that I may have brought up in a thread already somewhere is that these things only really apply to laptops, so maybe we should have a galliumos-laptop package so that these changes don't get installed on Chromeboxes and Chromebases.

**Comment by hugegreenbug** [comment]
Sure, a laptop package makes sense.

Hugh

**Comment by ColtonDRG** [comment]
I've created a galliumos-laptop package. Future discussion on this issue should take place in the galliumos-laptop issue tracker because that's where the issue belongs. A link to the issue on that tracker is here.
GalliumOS/galliumos-laptop#2
